/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITPM_INF;

import ITPM_codes.DBconnect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class addsession2 extends javax.swing.JFrame {

     Connection conn = null;
        java.sql.PreparedStatement pst = null;
        ResultSet rs = null;    
    
    public addsession2() {
        initComponents();
           conn = DBconnect.connect();
    }
    
       public void clear(){
   
        lectext.setText("");
        lecbox.setSelectedIndex(0);
        lectag.setSelectedIndex(0);
        grbox.setSelectedIndex(0);
        subbox.setSelectedIndex(0);
        numbox.setText("");
        subcode.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        grbox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subcode = new javax.swing.JTextField();
        numbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subbox = new javax.swing.JComboBox();
        n4but = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        cl6but = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lecbox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        lectag = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        lectext = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        bbut2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setText("                                                      Add session");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 120));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Step 2");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select group");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));

        grbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel2.add(grbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 290, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No of student");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Subject code");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 110, -1));
        jPanel2.add(subcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 290, 40));

        numbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numboxActionPerformed(evt);
            }
        });
        jPanel2.add(numbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 52, 280, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Select subject");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 30));

        subbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Introduction programming", "Object orinted concept", "Object orinted programming", "Data system", "Network Design model", "Data structure and algorithem", " " }));
        jPanel2.add(subbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 252, 300, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 1230, 330));

        n4but.setBackground(new java.awt.Color(255, 204, 204));
        n4but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n4but.setText("Next");
        n4but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4butActionPerformed(evt);
            }
        });
        jPanel1.add(n4but, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 900, 190, 40));

        submit.setBackground(new java.awt.Color(0, 0, 204));
        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 900, 110, 40));

        cl6but.setBackground(new java.awt.Color(255, 51, 255));
        cl6but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cl6but.setText("Clear");
        cl6but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl6butActionPerformed(evt);
            }
        });
        jPanel1.add(cl6but, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 900, 110, 40));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 840, -1));

        jLabel8.setBackground(new java.awt.Color(255, 0, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Select lectures & tag");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 250, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Step 1");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Select lecturer(s)");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, -1));

        lecbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lecbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "kumara", "kamal", "nimal", "aruna", "upul", "susantha", "nadishani", "oshadi" }));
        jPanel3.add(lecbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 290, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText(" Select tag");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 110, 30));

        lectag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lectag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "lecturer ", "assistent", "co-lecturere", "profeceor", "instructor" }));
        jPanel3.add(lectag, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 310, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Select lecturer2(s)");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, 30));

        lectext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectextActionPerformed(evt);
            }
        });
        jPanel3.add(lectext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 540, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 1230, 310));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Select group & subject");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 280, -1));

        bbut2.setBackground(new java.awt.Color(255, 204, 204));
        bbut2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbut2.setText("Back");
        bbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbut2ActionPerformed(evt);
            }
        });
        jPanel1.add(bbut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void n4butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4butActionPerformed
       
        this.toBack();
        managesession newFrame = new managesession();
        newFrame.setVisible(true);
        newFrame.toFront();
        
        
    }//GEN-LAST:event_n4butActionPerformed

    private void numboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numboxActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        String lec2name;
        String lec1name;
        String letag;
        int group;
        String subject;
        int nostudent;
        int scode;
         
        lec1name = lectext.getText();
        lec2name = lecbox.getSelectedItem().toString();
        scode = Integer.parseInt(subcode.getText());
        subject = subbox.getSelectedItem().toString();
        group = Integer.parseInt(grbox.getSelectedItem().toString());
        letag = lectag.getSelectedItem().toString();
        nostudent = Integer.parseInt(numbox.getText());
     
        
        try {
            
            String sql = "INSERT INTO manegesession (lec1,lec2,subcode,subname,grpid,lectag,student)VALUES ('"+lec1name+"','"+lec2name+"','"+scode+"','"+subject+"','"+group+"','"+letag+"','"+nostudent+"')";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "SUCCESS!");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_submitActionPerformed

    private void lectextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectextActionPerformed

    private void cl6butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl6butActionPerformed
        clear();
    }//GEN-LAST:event_cl6butActionPerformed

    private void bbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbut2ActionPerformed
       
        this.toBack();
        setVisible(false);
        new add_location().toFront();
        new add_location().setState(java.awt.Frame.NORMAL);
        
    }//GEN-LAST:event_bbut2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addsession2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addsession2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addsession2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addsession2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addsession2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbut2;
    private javax.swing.JButton cl6but;
    private javax.swing.JComboBox grbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox lecbox;
    private javax.swing.JComboBox lectag;
    private javax.swing.JTextField lectext;
    private javax.swing.JButton n4but;
    private javax.swing.JTextField numbox;
    private javax.swing.JComboBox subbox;
    private javax.swing.JTextField subcode;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
