
package ITPM_INF;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




public class lecturer extends javax.swing.JFrame {
     
     
    public lecturer() {
        initComponents();
      
      }
    
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void clear(){
    
        lecname.setText("");
        empidbox.setText("");
        fac.setSelectedIndex(0);
        dept.setSelectedIndex(0);
        centre.setSelectedIndex(0);
        buld.setSelectedIndex(0);
        levl.setSelectedIndex(0);
        ran.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sbut = new javax.swing.JButton();
        clbut = new javax.swing.JButton();
        genbut = new javax.swing.JButton();
        ran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        levl = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        buld = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        centre = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox();
        fac = new javax.swing.JComboBox();
        empidbox = new javax.swing.JTextField();
        lecname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        xbut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sbut.setBackground(new java.awt.Color(0, 51, 204));
        sbut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sbut.setText("Save");
        sbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbutActionPerformed(evt);
            }
        });
        jPanel1.add(sbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 100, 40));

        clbut.setBackground(new java.awt.Color(255, 51, 51));
        clbut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clbut.setText("Clear");
        clbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clbutActionPerformed(evt);
            }
        });
        jPanel1.add(clbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 110, 40));

        genbut.setBackground(new java.awt.Color(102, 255, 0));
        genbut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genbut.setText("Genarate Rank");
        genbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genbutActionPerformed(evt);
            }
        });
        jPanel1.add(genbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 210, 40));

        ran.setToolTipText("enter the rank");
        ran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranActionPerformed(evt);
            }
        });
        jPanel1.add(ran, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 270, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Rank");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 80, -1));

        levl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5" }));
        levl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levlActionPerformed(evt);
            }
        });
        jPanel1.add(levl, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 260, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Level");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 70, -1));

        buld.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "B502", "A301", "E201", "B302" }));
        jPanel1.add(buld, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 260, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Building");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 80, -1));

        centre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Malabe", "Kandy", "Mathara", "Kurunagala", "Jaffna" }));
        centre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centreActionPerformed(evt);
            }
        });
        jPanel1.add(centre, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 260, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Center");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 80, -1));

        jLabel1.setBackground(new java.awt.Color(102, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("                  Add lecturer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 600, 60));

        dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "information technology", "software Engineering", "cyber security", "computersystem and Networking", "Data Science", "interractive Media" }));
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 320, 40));

        fac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Computing", "Enginnering", "Humanity and science", "Buisness Manegement" }));
        jPanel1.add(fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 320, 40));

        empidbox.setToolTipText("enter the id");
        jPanel1.add(empidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 320, 40));

        lecname.setToolTipText("enter the lecturer name");
        lecname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecnameActionPerformed(evt);
            }
        });
        jPanel1.add(lecname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 320, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Department");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Faculty");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Employee ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lecturer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 90));

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1230, 370));

        xbut.setBackground(new java.awt.Color(255, 204, 204));
        xbut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xbut.setText("Next");
        xbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbutActionPerformed(evt);
            }
        });
        jPanel1.add(xbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, 160, 40));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbutActionPerformed
            
           String lecnturename = lecname.getText();
           String employeeid = empidbox.getText();
           String faculty = fac.getSelectedItem().toString();
           String department = dept.getSelectedItem().toString();
           String center = centre.getSelectedItem().toString();
           String building = buld.getSelectedItem().toString();
           String level = levl.getSelectedItem().toString();
           String rank = ran.getText();
           
           
        
        try {
            
            
            
            Class.forName("org.sqlite.JDBC");
            conn =DriverManager.getConnection("jdbc:sqlite:itpm.db");
            pst = conn.prepareStatement("INSERT INTO `lectrure`(`name`, `empid`, `faculty`, `department`, `center`, `building`, `level`, `ran`) VALUES (?,?,?,?,?,?,?,?)");
            
            pst.setString(1,lecnturename);
            pst.setString(2,employeeid);
            pst.setString(3,faculty);
            pst.setString(4,department);
            pst.setString(5,center);
            pst.setString(6,building);
            pst.setString(7,level);
            pst.setString(8,rank);
            
          
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Saved Successfully");
           
    
                clear();
                       
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(lecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }  

    }//GEN-LAST:event_sbutActionPerformed

    private void clbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clbutActionPerformed
        clear();
    }//GEN-LAST:event_clbutActionPerformed

    private void genbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genbutActionPerformed
       // String empid = empidbox.getText().toString();

        /* professor 1
        Assitant Professor 2
        Senior Lecturer(HG) 3
        Seniour Lecturer 4
        Lecturer 5
        Assiatant Lecturer 6

        */
       // int lvl =0;

       // if("professor"== levbox.getSelectedItem().toString()){

           // lvl =1;
       // }
       // if("Assistant Professeor"== levbox.getSelectedItem().toString()){
           // lvl=2;
       // }
        //if("Senior Lecturer(HG)"== levbox.getSelectedItem().toString()){
          //  lvl=3;
        //}
       // if("Senior Lecturer"== levbox.getSelectedItem().toString())//{
           // lvl=4;
        //}
       // if("Lecturer"== levbox.getSelectedItem().toString()){
           // lvl=5;
      //  }
        //if("Assistant Lecturer "== levbox.getSelectedItem().toString()){
            //lvl=6;
      //  }
    }//GEN-LAST:event_genbutActionPerformed

    private void ranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ranActionPerformed

    private void levlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levlActionPerformed

    }//GEN-LAST:event_levlActionPerformed

    private void centreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centreActionPerformed

    private void lecnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecnameActionPerformed

    private void xbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbutActionPerformed
      
        this.toBack();
        lecturermanege newFrame = new lecturermanege();
        newFrame.setVisible(true);
        newFrame.toFront();
        
        
    }//GEN-LAST:event_xbutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         
        this.toBack();
        setVisible(false);
        new TimeSlots().toFront();
        new TimeSlots().setState(java.awt.Frame.NORMAL);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox buld;
    private javax.swing.JComboBox centre;
    private javax.swing.JButton clbut;
    private javax.swing.JComboBox dept;
    private javax.swing.JTextField empidbox;
    private javax.swing.JComboBox fac;
    private javax.swing.JButton genbut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lecname;
    private javax.swing.JComboBox levl;
    private javax.swing.JTextField ran;
    private javax.swing.JButton sbut;
    private javax.swing.JButton xbut;
    // End of variables declaration//GEN-END:variables
}
