
package member2ineterface;



import codetest.dbconnect1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class lecturermanege extends javax.swing.JFrame {
    Connection conn1 = null;
    PreparedStatement pst = null;
     ResultSet rs = null;

   
    public lecturermanege() {
        initComponents();
         conn1 = dbconnect1.connect1();
        
        tableload();
      
    }
     public void tableload(){
       
        try {
            
            String sql = "SELECT id,name,empid,faculty,department,center,building,level,ran FROM lectrure";
            pst = (PreparedStatement) conn1.prepareStatement(sql);
            rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    
    }
     public void tabledata(){
        int r  = table1.getSelectedRow();
        
        String ID = table1.getValueAt(r, 0).toString();
        String NAME = table1.getValueAt(r, 1).toString();
        String employeeid =  table1.getValueAt(r, 2).toString();
        String fac =  table1.getValueAt(r, 3).toString();
        String dep =  table1.getValueAt(r, 4).toString();
        String cen =  table1.getValueAt(r, 5).toString();
        String build =  table1.getValueAt(r, 6).toString();
        String lev =  table1.getValueAt(r, 7).toString();
        String rank = table1.getValueAt(r, 8).toString();
        
        idbox1.setText(ID);
        lecname2.setText(NAME);
        empidbox2.setText(employeeid);
        facbox2.setSelectedItem(fac);
        depbox2.setSelectedItem(dep);
        cenbox2.setSelectedItem(cen);
        builbox2.setSelectedItem(build);
        levbox2.setSelectedItem(lev);
        rankbox2.setText(rank);
        
        
    }
     
       public void update(){
    
        String ID = idbox1.getText();
        String name = lecname2.getText();
        String employeeid = empidbox2.getText();
        String facul = facbox2.getSelectedItem().toString();
        String dep = depbox2.getSelectedItem().toString();
        String cent = cenbox2.getSelectedItem().toString();
        String build = builbox2.getSelectedItem().toString();
        String lev = levbox2.getSelectedItem().toString();
        String rank1 = rankbox2.getText();
        
        try {
            
            String sql = "UPDATE lectrure SET name='"+name+"',empid='"+employeeid+"',faculty='"+facul+"',department='"+dep+"',center='"+cent +"',building='"+build+"',level='"+lev+"', ran='"+rank1+"'WHERE id='"+ID+"'";
            pst = (PreparedStatement) conn1.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATED!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erorr");
        }
    
        tableload();
    }
    public void clear(){
    
        lecname2.setText("");
        empidbox2.setText("");
        facbox2.setSelectedIndex(0);
        depbox2.setSelectedIndex(0);
        cenbox2.setSelectedIndex(0);
        builbox2.setSelectedIndex(0);
        levbox2.setSelectedIndex(0);
        rankbox2.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        updat2 = new javax.swing.JButton();
        cle2but = new javax.swing.JButton();
        delete1but = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        depbox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        facbox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        empidbox2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lecname2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rankbox2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        levbox2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        builbox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cenbox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idbox1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backbut3 = new javax.swing.JButton();
        reeef = new javax.swing.JButton();
        n2but = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1302, 683));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Manege lecturer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "name", "employeeid", "faculty", "departmet", "center", "building", "level", "rank"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1270, 210));

        updat2.setBackground(new java.awt.Color(51, 255, 51));
        updat2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updat2.setText("Update");
        updat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updat2ActionPerformed(evt);
            }
        });
        jPanel1.add(updat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 90, 30));

        cle2but.setBackground(new java.awt.Color(255, 0, 255));
        cle2but.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cle2but.setText("Clear");
        cle2but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cle2butActionPerformed(evt);
            }
        });
        jPanel1.add(cle2but, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 100, 30));

        delete1but.setBackground(new java.awt.Color(255, 102, 102));
        delete1but.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete1but.setText("Delete");
        delete1but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1butActionPerformed(evt);
            }
        });
        jPanel1.add(delete1but, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 110, 30));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "information technology", "software Engineering", "cyber security", "computersystem and Networking", "Data Science", "interractive Media", "electrical and electronic", "megatroinc", "aircraft enginnering" }));
        depbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depbox2ActionPerformed(evt);
            }
        });
        jPanel2.add(depbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 320, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Department");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        facbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "computing", "Enginnering", "Humanity and science", "Buisness Manegement" }));
        jPanel2.add(facbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 320, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Faculty");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 40));

        empidbox2.setToolTipText("enter the id ");
        empidbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidbox2ActionPerformed(evt);
            }
        });
        jPanel2.add(empidbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 320, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Employee ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 40));

        lecname2.setToolTipText("Enter lecturer name");
        lecname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecname2ActionPerformed(evt);
            }
        });
        jPanel2.add(lecname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 320, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lecturer Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        rankbox2.setToolTipText("enter the rank");
        rankbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankbox2ActionPerformed(evt);
            }
        });
        jPanel2.add(rankbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 270, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Rank");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 80, -1));

        levbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5" }));
        jPanel2.add(levbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 260, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Level");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 70, -1));

        builbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "B502", "A301", "E201", "B302" }));
        jPanel2.add(builbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 260, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Building");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 80, -1));

        cenbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Malabe", "Kandy", "Mathara", "Kurunagala", "Jaffna" }));
        cenbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenbox2ActionPerformed(evt);
            }
        });
        jPanel2.add(cenbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 260, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Center");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        idbox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idbox1.setText("ID");
        jPanel2.add(idbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 1110, 400));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 90));

        backbut3.setBackground(new java.awt.Color(204, 0, 0));
        backbut3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbut3.setText("Back");
        backbut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbut3ActionPerformed(evt);
            }
        });
        jPanel1.add(backbut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 40));

        reeef.setBackground(new java.awt.Color(255, 51, 51));
        reeef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reeef.setText("Refresh");
        jPanel1.add(reeef, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 520, 100, 50));

        n2but.setBackground(new java.awt.Color(255, 51, 51));
        n2but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n2but.setText("Next");
        n2but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2butActionPerformed(evt);
            }
        });
        jPanel1.add(n2but, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 310, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updat2ActionPerformed
        update();
        tableload();
    }//GEN-LAST:event_updat2ActionPerformed

    private void cle2butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cle2butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cle2butActionPerformed

    private void delete1butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1butActionPerformed
        int check = JOptionPane.showConfirmDialog(null, "are your sure");

        if(check==0){

            String ID = idbox1.getText();

            try {
                String sql = "DELETE FROM lectrure WHERE id='"+ID+"'  ";
                pst = (PreparedStatement) conn1.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "DELETED");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "can't delete");
            }

        }

        tableload();
    }//GEN-LAST:event_delete1butActionPerformed

    private void rankbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankbox2ActionPerformed

    private void cenbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cenbox2ActionPerformed

    private void lecname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecname2ActionPerformed

    private void depbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depbox2ActionPerformed

    private void empidbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empidbox2ActionPerformed

    private void backbut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbut3ActionPerformed
        lecturer n1 = new lecturer();
        n1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbut3ActionPerformed

    private void n2butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2butActionPerformed
        subject p1 = new subject ();
        p1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_n2butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturermanege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturermanege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturermanege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturermanege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturermanege().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbut3;
    private javax.swing.JComboBox builbox2;
    private javax.swing.JComboBox cenbox2;
    private javax.swing.JButton cle2but;
    private javax.swing.JButton delete1but;
    private javax.swing.JComboBox depbox2;
    private javax.swing.JTextField empidbox2;
    private javax.swing.JComboBox facbox2;
    private javax.swing.JLabel idbox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lecname2;
    private javax.swing.JComboBox levbox2;
    private javax.swing.JButton n2but;
    private javax.swing.JTextField rankbox2;
    private javax.swing.JButton reeef;
    private javax.swing.JTable table1;
    private javax.swing.JButton updat2;
    // End of variables declaration//GEN-END:variables
}
