/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Member_03;

import com.sun.jmx.defaults.JmxProperties;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class WorkingDays extends javax.swing.JFrame {

    /**
     * Creates new form WorkingDays
     */
    public WorkingDays() {
        initComponents();
        table_update();
    }
 
    Connection con1;
    PreparedStatement pst;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnoworkingdays = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        checkmon = new javax.swing.JCheckBox();
        checktue = new javax.swing.JCheckBox();
        checkwed = new javax.swing.JCheckBox();
        checkthu = new javax.swing.JCheckBox();
        checkfri = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtworkhrs = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtworkmin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_workingdays = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("                                   Manage Working Days and Hours");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setText("No of Working Days");

        txtnoworkingdays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "01", "02", "03", "04", "05" }));
        txtnoworkingdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoworkingdaysActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText("Working Days");

        checkmon.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        checkmon.setText("Monday");
        checkmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkmonActionPerformed(evt);
            }
        });

        checktue.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        checktue.setText("Tuesday");
        checktue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checktueActionPerformed(evt);
            }
        });

        checkwed.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        checkwed.setText("Wednesday");

        checkthu.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        checkthu.setText("Thursday");
        checkthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkthuActionPerformed(evt);
            }
        });

        checkfri.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        checkfri.setText("Friday");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setText("Working Time Per Day");

        txtworkhrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "01", "02", "03", "04", "05", "06", "07", "08", "09" }));
        txtworkhrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtworkhrsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Hours");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Minutes");

        txtworkmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "00" }));
        txtworkmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtworkminActionPerformed(evt);
            }
        });

        jTable_workingdays.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable_workingdays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "No of Working Days", "Working Days", "Working Time Per Day(hrs)", "Working Time Per Day(min)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_workingdays.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable_workingdays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_workingdaysMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_workingdays);

        jButton4.setBackground(new java.awt.Color(255, 102, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 255, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText("Save");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton6.setText("Update");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton7.setText("Next");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(txtnoworkingdays, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checktue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkwed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkfri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkmon, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 26, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtworkhrs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtworkmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnoworkingdays, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkmon)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checktue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkwed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkthu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkfri)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtworkhrs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtworkmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        jLabel1.getAccessibleContext().setAccessibleName("                                 Manage Working Days and Hours");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //UPDATE TABLE
    private void table_update()
    {
        try {
            
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/itpm","root","");
               String sql = ("select `ID`,`No of Working Days`,`Working Days`,`Working Time Per Day(hrs)`,`Working Time Per Day(min)` from working_days");
                pst = con1.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                jTable_workingdays.setModel(DbUtils.resultSetToTableModel(rs));
               
 
    
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
    
    
    private void txtnoworkingdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoworkingdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoworkingdaysActionPerformed

    private void checktueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checktueActionPerformed

    private void txtworkminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtworkminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtworkminActionPerformed

    private void txtworkhrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtworkhrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtworkhrsActionPerformed

    private void checkthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkthuActionPerformed

    private void checkmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkmonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkmonActionPerformed

    
    //SAVE BUTTON
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         
        String noworkingdays = txtnoworkingdays.getSelectedItem().toString();
        
                
        String workhrs = txtworkhrs.getSelectedItem().toString();
        String workmin = txtworkmin.getSelectedItem().toString();
        
        try {
            
            
            
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/itpm","root","");
            pst = con1.prepareStatement("INSERT INTO `working_days`(`No of Working Days`, `Working Days`, `Working Time Per Day(hrs)`, `Working Time Per Day(min)`) VALUES (?,?,?,?)");

            
            pst.setString(1, noworkingdays);
            
            String workingdays="";
            if(checkmon.isSelected()){
            workingdays+=checkmon.getText()+" ";
             }
            if(checktue.isSelected()){
            workingdays+=checktue.getText()+" ";
             }
             if(checkwed.isSelected()){
            workingdays+=checkwed.getText()+" ";
             }    
              if(checkthu.isSelected()){
            workingdays+=checkthu.getText()+" ";
             }   
              if(checkfri.isSelected()){
            workingdays+=checkfri.getText()+" ";
             }   
          
            pst.setString(2, workingdays);
            pst.setString(3, workhrs);
            pst.setString(4, workmin);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Working Days and Hours Saved Successfully");
            table_update();
            
            txtnoworkingdays.setSelectedIndex(0);
            
            checkmon.setSelected(false);
            checktue.setSelected(false);
            checkwed.setSelected(false);
            checkthu.setSelected(false);
            checkfri.setSelected(false);
            
            txtworkhrs.setSelectedIndex(0);
            txtworkmin.setSelectedIndex(0);
            
            txtnoworkingdays.requestFocus();
            

            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

  
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    
    //SELECT ROW AND DISPLAY IN FIELDS NOT DISPLAY WHEN 2 CLICKED SEPERATELY 
    private void jTable_workingdaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_workingdaysMouseClicked
        // TODO add your handling code here:
        
        int d1 = jTable_workingdays.getSelectedRow();
        TableModel model =jTable_workingdays.getModel();

           
        String noworkingdays = model.getValueAt(d1, 1).toString();
            switch (noworkingdays){
                case  "Select":
                    txtnoworkingdays.setSelectedIndex(0);
                     break;
                     
                case  "01":
                    txtnoworkingdays.setSelectedIndex(1);
                     break;
                     
                case  "02":
                    txtnoworkingdays.setSelectedIndex(2);
                     break;
                     
                case  "03":
                    txtnoworkingdays.setSelectedIndex(3);
                     break;
                     
                case  "04":
                    txtnoworkingdays.setSelectedIndex(4);
                     break;
                     
                case  "05":
                    txtnoworkingdays.setSelectedIndex(5);
                     break;
                     
                case  "06":
                    txtnoworkingdays.setSelectedIndex(6);
                     break;
                  
                case  "07":
                    txtnoworkingdays.setSelectedIndex(7);
                     break;
               }
            
           String workingdays = model.getValueAt(d1, 2).toString();
            
        
          
                  
            switch (workingdays){
                    case  "Monday ":
                    checkmon.setSelected(true);
                    checktue.setSelected(false);
                    checkwed.setSelected(false);
                    checkthu.setSelected(false);
                    checkfri.setSelected(false);
                    break;
             
                    case  "Tuesday ":
                    checktue.setSelected(true);
                    checkmon.setSelected(false);
                    checkwed.setSelected(false);
                    checkthu.setSelected(false);
                    checkfri.setSelected(false);
                    break;
                    
                    case  "Wednesday ":
                    checkwed.setSelected(true);
                    checkmon.setSelected(false);
                    checktue.setSelected(false);
                    checkthu.setSelected(false);
                    checkfri.setSelected(false);
                    break;
                    
                    case  "Thursday ":
                    checkthu.setSelected(true);
                    checkmon.setSelected(false);
                    checktue.setSelected(false);
                    checkwed.setSelected(false);
                    checkfri.setSelected(false);
                    break;
                         
                    case  "Friday ":
                    checkfri.setSelected(true);
                    checkmon.setSelected(false);
                    checktue.setSelected(false);
                    checkwed.setSelected(false);
                    checkthu.setSelected(false);
                    break;
                    
                 
                    default:
                        checkmon.setSelected(true);
                        checktue.setSelected(true);
                        checkwed.setSelected(true);
                        checkthu.setSelected(true);
                        checkfri.setSelected(true);
                        break;
                        
                }      
                  
                        
                                      
            String workhrs = model.getValueAt(d1, 3).toString();
            
             switch (workhrs){
                 
                case  "Select":
                    txtworkhrs.setSelectedIndex(0);
                     break;
                 
                case  "01":
                    txtworkhrs.setSelectedIndex(1);
                     break;
                     
                case  "02":
                    txtworkhrs.setSelectedIndex(2);
                     break;
                     
                case  "03":
                    txtworkhrs.setSelectedIndex(3);
                     break;
                     
                case  "04":
                    txtworkhrs.setSelectedIndex(4);
                     break;
                     
                case  "05":
                    txtworkhrs.setSelectedIndex(5);
                     break;
                     
                case  "06":
                    txtworkhrs.setSelectedIndex(6);
                     break;
                     
                case  "07":
                    txtworkhrs.setSelectedIndex(7);
                     break;
                     
                case  "08":
                    txtworkhrs.setSelectedIndex(8);
                     break;
                     
                case  "09":
                    txtworkhrs.setSelectedIndex(9);
                     break;
               }
             
             
             String workmin = model.getValueAt(d1, 4).toString();
             
                switch (workmin){
                    
                case  "Select":
                    txtworkmin.setSelectedIndex(0);
                     break;
                    
                case  "00":
                    txtworkmin.setSelectedIndex(1);
                     break;
                    
                }  
        
    }//GEN-LAST:event_jTable_workingdaysMouseClicked

    
    //DELETE BUTTON
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel d1 = (DefaultTableModel)jTable_workingdays.getModel();
      int selectIndex = jTable_workingdays.getSelectedRow();
        
      int ID = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());  
        
      int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the Working Days and Hours","Warning",JOptionPane.YES_NO_OPTION);
      
      if(dialogResult == JOptionPane.YES_OPTION)
      {
          try {
              Class.forName("com.mysql.jdbc.Driver");
             con1 = DriverManager.getConnection("jdbc:mysql://localhost/itpm","root","");
             pst = con1.prepareStatement("DELETE FROM `working_days` WHERE `ID`=? ");
             pst.setInt(1, ID);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(this,"Working Days and Hours Deleted");
            table_update();
            
           
            txtnoworkingdays.setSelectedIndex(0);
            txtworkhrs.setSelectedIndex(0);
            txtworkmin.setSelectedIndex(0);
            checkmon.setSelected(false);
            checktue.setSelected(false);
            checkwed.setSelected(false);
            checkthu.setSelected(false);
            checkfri.setSelected(false);
            
            txtnoworkingdays.requestFocus();
            
             
              
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
          }
            
      }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    
    //UPDATE BUTTON
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
       DefaultTableModel d1 = (DefaultTableModel)jTable_workingdays.getModel();
        int selectIndex = jTable_workingdays.getSelectedRow();
       
        int ID = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());  
       
        
        String noworkingdays = txtnoworkingdays.getSelectedItem().toString();
        String workhrs = txtworkhrs.getSelectedItem().toString();
        String workmin = txtworkmin.getSelectedItem().toString();
  
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con1 = DriverManager.getConnection("jdbc:mysql://localhost/itpm","root","");
             pst = con1.prepareStatement("UPDATE `working_days` SET `No of Working Days`=?,`Working Days`=?,`Working Time Per Day(hrs)`=?,`Working Time Per Day(min)`=? WHERE ID=?");

           pst.setString(1, noworkingdays);
            
            String workingdays="";
            if(checkmon.isSelected()){
            workingdays+=checkmon.getText()+" ";
             }
            if(checktue.isSelected()){
            workingdays+=checktue.getText()+" ";
             }
             if(checkwed.isSelected()){
            workingdays+=checkwed.getText()+" ";
             }    
              if(checkthu.isSelected()){
            workingdays+=checkthu.getText()+" ";
             }   
              if(checkfri.isSelected()){
            workingdays+=checkfri.getText()+" ";
             }   
               
            pst.setString(2, workingdays);
            pst.setString(3, workhrs);
            pst.setString(4, workmin);
            pst.setInt(5, ID);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Working Days and Hours Updated");
            table_update();
            
            txtnoworkingdays.setSelectedIndex(0);
            
            checkmon.setSelected(false);
            checktue.setSelected(false);
            checkwed.setSelected(false);
            checkthu.setSelected(false);
            checkfri.setSelected(false);
        
            txtworkhrs.setSelectedIndex(0);
            txtworkmin.setSelectedIndex(0);
            
            txtnoworkingdays.requestFocus();
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);    
        
      } catch (SQLException ex) {   
            Logger.getLogger(WorkingDays.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    //CLEAR BUTTON
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         txtnoworkingdays.setSelectedIndex(0);
         checkmon.setSelected(false);
         checktue.setSelected(false);
         checkwed.setSelected(false);
         checkthu.setSelected(false);
         checkfri.setSelected(false);
         txtworkhrs.setSelectedIndex(0);
         txtworkmin.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    
    //NEXT BUTTON
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        this.toBack();
        TimeSlots newFrame = new TimeSlots();
        newFrame.setVisible(true);
        newFrame.toFront();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    
    //BACK BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.toBack();
        setVisible(false);
        new Home().toFront();
        new Home().setState(java.awt.Frame.NORMAL);
        
    }//GEN-LAST:event_jButton1ActionPerformed

  

                                   

                          

      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkingDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkfri;
    private javax.swing.JCheckBox checkmon;
    private javax.swing.JCheckBox checkthu;
    private javax.swing.JCheckBox checktue;
    private javax.swing.JCheckBox checkwed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_workingdays;
    private javax.swing.JComboBox<String> txtnoworkingdays;
    private javax.swing.JComboBox<String> txtworkhrs;
    private javax.swing.JComboBox<String> txtworkmin;
    // End of variables declaration//GEN-END:variables
}
